############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Us"
url = "/authors"
weight = 2

[[main]]
name = "Résumé"
url = "/resume"
weight = 2

[[main]]
parent = "Résumé"
name = "LakSom"
url = "/resume/lak-som"

#[[main]]
#parent = "Résumé"
#name = "AchIyy"
#url = "/resume/ach-iyy"

#[[main]]
#name = "Elements"
#url = "/elements"
#weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"

[[main]]
parent = "Pages"
name = "Contact Us"
url = "/contact"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"
#
#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

#[[footer]]
#name = "Elements"
#url = "/elements"
#weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
